# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: commit
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        if git diff --quiet; then
            echo No changes, not commiting
        else
            git add .
            git commit -m "build"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/dzej0/threejs_charge_sim HEAD:main
        fi

  update-portfolio:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: trigger build and deploy scripts at portfolio repo
      uses: peter-evans/repository_dispatch@v3
      with:
        repository: dzej0/dzej0.github.com
        event-type: "update_projects"
